/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#f59e0b",
        "primary-fixed": "#ffddb8",
        "on-tertiary-container": "#4a4424",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "background": "#f8f9ff",
        "secondary-fixed-dim": "#ffb783",
        "error-container": "#ffdad6",
        "on-background": "#121c2a",
        "inverse-primary": "#ffb95f",
        "on-primary": "#ffffff",
        "on-secondary-container": "#693300",
        "on-primary-fixed-variant": "#653e00",
        "inverse-surface": "#27313f",
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#bab189",
        "surface-dim": "#d0dbed",
        "surface-container-highest": "#d9e3f6",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed-dim": "#d1c79d",
        "on-tertiary-fixed-variant": "#4d4727",
        "on-error": "#ffffff",
        "on-surface-variant": "#534434",
        "outline": "#867461",
        "outline-variant": "#d8c3ad",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fd933d",
        "secondary-fixed": "#ffdcc5",
        "tertiary-fixed": "#ede3b8",
        "on-primary-container": "#613b00",
        "secondary": "#944a00",
        "on-secondary-fixed-variant": "#713700",
        "on-secondary-fixed": "#301400",
        "surface": "#f8f9ff",
        "on-primary-fixed": "#2a1700",
        "surface-variant": "#d9e3f6",
        "on-surface": "#121c2a",
        "tertiary": "#665f3d",
        "primary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#201c02",
        "primary": "#855300",
        "surface-tint": "#855300",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eaf1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "stack-sm": "12px",
        "unit": "8px",
        "margin-mobile": "20px",
        "stack-lg": "48px",
        "stack-md": "24px",
        "margin-desktop": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "label-md": ["DM Sans"],
        "headline-md": ["DM Sans"],
        "display-lg-mobile": ["DM Sans"],
        "headline-lg": ["DM Sans"],
        "body-md": ["DM Sans"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "display-lg-mobile": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
